codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  range: "75...100"
  round: down

  status:
    project:
      default:
        target: 90%
        threshold: 4%
    patch: no
    changes: no
